/** @type {import('tailwindcss').Config} */
export default {
  darkMode: ['class'],
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        abi: {
          bg: '#0a0907',
          'bg-elevated': '#12100d',
          'bg-card': '#191511',
          'bg-hover': '#241a13',
          border: '#3a3027',
          'border-glow': '#60432c',
          orange: '#FF6B0A',
          'orange-light': '#FF8738',
          'orange-dark': '#C94F00',
          text: '#f5f0e8',
          'text-muted': '#c6bdb2',
          'text-dim': '#8f8378',
          success: '#2bd978',
          warning: '#ffb126',
          danger: '#ff4057',
          info: '#73a8d9',
        },
        semantic: {
          primary: 'var(--text-primary)',
          secondary: 'var(--text-secondary)',
          muted: 'var(--text-muted)',
          positive: 'var(--text-positive)',
          negative: 'var(--text-negative)',
          warning: 'var(--text-warning)',
          accent: 'var(--text-accent)',
        },
        background: 'var(--background)',
        foreground: 'var(--foreground)',
        card: {
          DEFAULT: 'var(--card)',
          foreground: 'var(--card-foreground)',
        },
        popover: {
          DEFAULT: 'var(--popover)',
          foreground: 'var(--popover-foreground)',
        },
        primary: {
          DEFAULT: 'var(--primary)',
          foreground: 'var(--primary-foreground)',
        },
        secondary: {
          DEFAULT: 'var(--secondary)',
          foreground: 'var(--secondary-foreground)',
        },
        muted: {
          DEFAULT: 'var(--muted)',
          foreground: 'var(--muted-foreground)',
        },
        accent: {
          DEFAULT: 'var(--accent)',
          foreground: 'var(--accent-foreground)',
        },
        destructive: {
          DEFAULT: 'var(--destructive)',
          foreground: 'var(--destructive-foreground, var(--destructive))',
        },
        border: 'var(--border)',
        input: 'var(--input)',
        ring: 'var(--ring)',
        chart: {
          1: 'var(--chart-1)',
          2: 'var(--chart-2)',
          3: 'var(--chart-3)',
          4: 'var(--chart-4)',
          5: 'var(--chart-5)',
        },
        sidebar: {
          DEFAULT: 'var(--sidebar)',
          foreground: 'var(--sidebar-foreground)',
          primary: 'var(--sidebar-primary)',
          'primary-foreground': 'var(--sidebar-primary-foreground)',
          accent: 'var(--sidebar-accent)',
          'accent-foreground': 'var(--sidebar-accent-foreground)',
          border: 'var(--sidebar-border)',
          ring: 'var(--sidebar-ring)',
        },
      },
      fontFamily: {
        sans: ['Oxanium Variable', 'Oxanium', 'system-ui', 'sans-serif'],
        display: ['Oxanium Variable', 'Oxanium', 'system-ui', 'sans-serif'],
        orbitron: ['Oxanium Variable', 'Oxanium', 'system-ui', 'sans-serif'],
        rajdhani: ['Oxanium', 'sans-serif'],
        mono: ['Oxanium Variable', 'Oxanium', 'system-ui', 'sans-serif'],
      },
      borderRadius: {
        DEFAULT: '2px',
        sm: 'calc(var(--radius) - 4px)',
        md: 'calc(var(--radius) - 2px)',
        lg: 'var(--radius)',
        xl: 'calc(var(--radius) + 4px)',
        '2xl': 'calc(var(--radius) + 8px)',
      },
      boxShadow: {
        glow: '0 0 0 1px rgba(255, 107, 10, 0.38), 0 8px 24px rgba(5, 3, 1, 0.5)',
        'glow-sm': '0 0 0 1px rgba(255, 107, 10, 0.3)',
        'glow-lg': '0 0 0 1px rgba(255, 107, 10, 0.5), 0 12px 32px rgba(5, 3, 1, 0.6)',
        card: '0 1px 0 rgba(255, 245, 230, 0.04) inset, 0 8px 24px rgba(0, 0, 0, 0.35)',
        elevated: '0 1px 0 rgba(255, 245, 230, 0.05) inset, 0 16px 40px rgba(0, 0, 0, 0.5)',
      },
      animation: {
        float: 'float 6s ease-in-out infinite',
        'pulse-glow': 'pulse-glow 2.4s ease-in-out infinite',
        'scan-line': 'scan-line 8s linear infinite',
        'slide-up': 'slide-up 0.28s cubic-bezier(0.22, 1, 0.36, 1)',
        'fade-in': 'fade-in 0.2s ease-out',
        'border-flow': 'border-flow 2s linear infinite',
      },
      keyframes: {
        float: {
          '0%, 100%': { transform: 'translateY(0)' },
          '50%': { transform: 'translateY(-6px)' },
        },
        'pulse-glow': {
          '0%, 100%': { boxShadow: '0 0 0 1px rgba(255, 107, 10, 0.3)' },
          '50%': { boxShadow: '0 0 0 1px rgba(255, 107, 10, 0.58)' },
        },
        'scan-line': {
          '0%': { transform: 'translateY(-100%)' },
          '100%': { transform: 'translateY(100%)' },
        },
        'slide-up': {
          '0%': { opacity: '0', transform: 'translateY(12px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        'fade-in': {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        'border-flow': {
          '0%': { backgroundPosition: '0% 50%' },
          '100%': { backgroundPosition: '200% 50%' },
        },
      },
    },
  },
  plugins: [],
};
